### ISSUE TITLE
Old - New: Medical Students with Disabilities 

### ISSUE THREAD

**Issue by erm619** [cfms-website/cfms-website.github.io#43]
The old CFMS website has a page dedicated to helping medical students with disabilities [http://www.old.cfms.org/index.php/resources-3/medical-students-with-disabilities.html](http://www.old.cfms.org/index.php/resources-3/medical-students-with-disabilities.html)

This could be incorporated to the new CFMS website under [www.cfms.org/what-we-do/student-affairs](url)

This also needs to be updated

**Comment by Threatsignal** [comment]
@VP-Communications When this pull request is merged into the websites staging branch, this page will display on the website.
Will be a milestone for now because I used the information from the old website However you guys said it needs to be updated.
I made it available for editing through the editable class, However, if needed I can put the new information in there quickly if you provide me with it. Let me know, thanks!

**Comment by Threatsignal** [comment]
See Pull Request #81

**Comment by Threatsignal** [comment]
See #123
